---
- name: Install Nginx
  hosts: web_servers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes
    
    - name: Install Nginx
      apt:
        name: nginx
        state: present
      become: yes